#!/bin/bash
#
# $Id: gdbline,v 1.1 2004/08/02 16:27:55 corbet Exp $
#
# gdbline module image
#
# Outputs an add-symbol-file line suitable for pasting into gdb to examine
# a loaded module.
# [kods] the command line to execute this script is like following line.
# [kods] "sudo ./gdbline scull ~/git/scull/scull/scull.ko"
# [kods] $1: "scull"
# [kods] $2: "~/git/scull/scull/scull.ko"
#
if [ "$#" -ne 2 ]; then
    echo 'specify the following value as parameters. $1: scull, $2: ~/git/scull/scull/scull.ko'
fi

cd /sys/module/$1/sections
if [ $? != 0 ]; then
    echo "scull module is not insmoded yet!"
    exit 1
fi
echo -n add-symbol-file $2 `/bin/cat .text`

for section in .[a-z]* *; do
    if [ $section != ".text" ]; then
	    echo  " \\"
	    echo -n "       -s" $section `/bin/cat $section`
    fi
done

echo
